name: Along with Symfony Deprecations

on:
    push:
        tags:
            - '*'

jobs:
    bare_run:
        runs-on: ubuntu-latest

        steps:
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    coverage: none

            -   run: mkdir nested-dir

            -   run: composer require symplify/easy-coding-standard --ansi
                working-directory: nested-dir

            -   run: composer require symfony/deprecation-contracts --ansi
                working-directory: nested-dir

            -   run: vendor/bin/ecs list --ansi --debug
                working-directory: nested-dir
